name: Deploy testing image

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/deploy-test-image.yml"

jobs:
  push-to-dockerhub:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v2

      - name: Login at DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: latest
          file: ./Dockerfile
